package org.common.entities.dbentities;
// Generated 2025 Oct 20 00:14:06 by Hibernate Tools 7.1.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,catalog="java_db_explorer"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Customers  implements java.io.Serializable {


     private Long id;
     private String name;
     private String email;
     private Timestamp createdAt;
     private Boolean active;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Customers() {
    }

	
    public Customers(String name, String email) {
        this.name = name;
        this.email = email;
    }
    public Customers(String name, String email, Timestamp createdAt, Boolean active, Set<Orders> orderses) {
       this.name = name;
       this.email = email;
       this.createdAt = createdAt;
       this.active = active;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


