package org.common.entities.dbentities;
// Generated 2025 Oct 20 15:11:04 by Hibernate Tools 7.1.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name="order_items"
    ,catalog="java_db_explorer"
)
public class OrderItems  implements java.io.Serializable {


     private Long id;
     private Products products;
     private Orders orders;
     private int quantity;
     private BigDecimal unitPrice;

    public OrderItems() {
    }

    public OrderItems(Products products, Orders orders, int quantity, BigDecimal unitPrice) {
       this.products = products;
       this.orders = orders;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="unit_price", nullable=false, precision=10, scale=2)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }




}


