package org.common.entities.dbentities;
// Generated 2025 Oct 20 15:11:04 by Hibernate Tools 7.1.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments"
    ,catalog="java_db_explorer"
    , uniqueConstraints = @UniqueConstraint(columnNames="order_id") 
)
public class Payments  implements java.io.Serializable {


     private Long id;
     private Orders orders;
     private String paymentMethod;
     private BigDecimal amount;
     private Timestamp paidAt;
     private Boolean successful;

    public Payments() {
    }

	
    public Payments(Orders orders, String paymentMethod, BigDecimal amount) {
        this.orders = orders;
        this.paymentMethod = paymentMethod;
        this.amount = amount;
    }
    public Payments(Orders orders, String paymentMethod, BigDecimal amount, Timestamp paidAt, Boolean successful) {
       this.orders = orders;
       this.paymentMethod = paymentMethod;
       this.amount = amount;
       this.paidAt = paidAt;
       this.successful = successful;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", unique=true, nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="payment_method", nullable=false, length=30)
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    
    @Column(name="amount", nullable=false, precision=10, scale=2)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="paid_at", length=19)
    public Timestamp getPaidAt() {
        return this.paidAt;
    }
    
    public void setPaidAt(Timestamp paidAt) {
        this.paidAt = paidAt;
    }

    
    @Column(name="successful")
    public Boolean getSuccessful() {
        return this.successful;
    }
    
    public void setSuccessful(Boolean successful) {
        this.successful = successful;
    }




}


