package org.common.entities.dbentities;
// Generated 2025 Oct 20 15:11:04 by Hibernate Tools 7.1.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="java_db_explorer"
)
public class Products  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private BigDecimal price;
     private Integer stockQuantity;
     private String category;
     private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

    public Products() {
    }

	
    public Products(String name, BigDecimal price) {
        this.name = name;
        this.price = price;
    }
    public Products(String name, String description, BigDecimal price, Integer stockQuantity, String category, Set<OrderItems> orderItemses) {
       this.name = name;
       this.description = description;
       this.price = price;
       this.stockQuantity = stockQuantity;
       this.category = category;
       this.orderItemses = orderItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=10, scale=2)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="stock_quantity")
    public Integer getStockQuantity() {
        return this.stockQuantity;
    }
    
    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    
    @Column(name="category", length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }




}


